require('lazy').setup({
  {
    "folke/which-key.nvim",
    init = function()
      vim.o.timeout = true
      vim.o.timeoutlen = 300
    end,
  },
  { 'nvim-treesitter/nvim-treesitter', build = ':TSUpdate' },
  'neovim/nvim-lspconfig',
  'airblade/vim-gitgutter',
  'ryanoasis/vim-devicons',
  'nvim-lualine/lualine.nvim',
  'kyazdani42/nvim-web-devicons',
  'navarasu/onedark.nvim',
  'scrooloose/syntastic',
  'nvim-lua/plenary.nvim',
  'nvimdev/lspsaga.nvim',
  'romgrk/barbar.nvim',
  'numToStr/Comment.nvim',
  'yamatsum/nvim-cursorline',
  'windwp/nvim-autopairs',
  'ggandor/lightspeed.nvim',
  { 'ms-jpq/chadtree', branch = 'chad', run = 'python3 -m chadtree deps' },
  'goolord/alpha-nvim',
  { 'ms-jpq/coq_nvim', branch = 'coq' },
  { 'ms-jpq/coq.artifacts', branch = 'artifacts' },
  'mfussenegger/nvim-dap',
  'rcarriga/nvim-dap-ui',
  'ray-x/lsp_signature.nvim',
  { 'nvim-telescope/telescope.nvim', requires = { 'nvim-lua/plenary.nvim' } },
  { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make', cond = vim.fn.executable "make" == 1 },
  'simrat39/rust-tools.nvim',
  'cdelledonne/vim-cmake',
})
