require "plugins.configs.alpha"
require "plugins.configs.barbar"
require "plugins.configs.dap"
require "plugins.configs.dapui"
-- require "plugins.configs.lsp_signature"
require "plugins.configs.lspconfig"
require "plugins.configs.lspsaga"
require "plugins.configs.lualine"
require "plugins.configs.nvim-treesitter"
require "plugins.configs.onedark"
require "plugins.configs.telescope"
require "plugins.configs.comment"
require "plugins.configs.nvim-autopairs"
require "plugins.configs.coq_nvim"
require "plugins.configs.which-key"
